<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Bharath" failures="1" tests="12" name="Test" time="2.121" errors="0" timestamp="2025-03-25T21:01:01 IST">
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.007"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.002"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.002"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.001"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.002"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.001"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.001"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.0"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.001"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.003"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase2" time="2.021">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.framework.testng.concepts.AppCommons.TestCase2() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.framework.testng.concepts.AppCommons.TestCase2() didn't finish within the time-out 2000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TestCase2 -->
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase3" time="0.0">
    <skipped/>
  </testcase> <!-- TestCase3 -->
</testsuite> <!-- Test -->
