<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Bharath" failures="1" tests="4" name="Test" time="0.055" errors="0" timestamp="2025-03-24T21:21:42 IST">
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.01">
    <failure type="java.lang.AssertionError" message="Test Case 1 failed">
      <![CDATA[java.lang.AssertionError: Test Case 1 failed
at com.framework.testng.concepts.AppCommons.TestCase1(AppCommons.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase2" time="0.001"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase3" time="0.003"/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase3" time="0.001"/>
</testsuite> <!-- Test -->
